### PR TITLE
Fix display

### PR DESCRIPTION
**Pull request by shenwilly**
Hi, I tried to fix the screen display overflow.

If it looks okay, I can do the rest of the menus (only the homepage & Trade menus are proper right now)

### CODE REVIEW

**Comment by antoncoding** [comment]
> Hi, I tried to fix the screen display overflow.
> 
> If it looks okay, I can do the rest of the menus (only the homepage & Trade menus are proper right now)

thanks a lot for helping this! It looks great! I'd love to have u work on the rest of the menu!

**Comment by antoncoding** [comment]
> Hi, I tried to fix the screen display overflow.
> 
> If it looks okay, I can do the rest of the menus (only the homepage & Trade menus are proper right now)

thanks for helping with this! but can we keep the Aragon <Layout/> component for the Homepage and Trade menu? I think it looks better with spaces on the side.
(or under what circumstances would it cause problem?)

**Comment by shenwilly** [comment]
Not sure why but the Aragon component cause a slight horizontal overflow, looks pretty bad on my screen ([13' inch display](https://screenfly.org/#u=https%3A//gammaportal.xyz/%23/&w=1280&h=800&a=1)) :o

**Comment by antoncoding** [comment]
> Not sure why but the Aragon component cause a slight horizontal overflow, cuts pretty bad on my screen ([13' inch display](https://screenfly.org/#u=https%3A//gammaportal.xyz/%23/&w=1280&h=800&a=1)) :o

got it. the only problem I see on a wider screen (24 inch monitor) is the padding on the left and right seem to be too small, the whole screen looks pretty flat:

image

maybe we can adjust this by using the built in off-set that `react-grid-system` provides?

**Comment by shenwilly** [comment]
How about this? We can setup the Container width for each breakpoints in `react-grid-system`

**Comment by antoncoding** [comment]
yeah stgm

**Review by antoncoding — APPROVED** [review]

**Comment by antoncoding** [comment]
@shenwilly thanks for fixing this! really appreciate it ;)

**Pull request merged**
